### ISSUE TITLE
希望能增加导入书签的功能

### ISSUE THREAD

**Issue by xovow** [iuv/jisuye#1]
其他建议：手机端编辑
                   每个分类可以收起来

**Comment by iuv** [comment]
导入书签以前做过是基于后端服务的，无后端的我看看能不能实现吧
另外手机端我好像没做适配现在手机上显示的跟pc端一样  进不了编辑状态吧。。

**Comment by xovow** [comment]
> 另外手机端我好像没做适配现在手机上显示的跟pc端一样 进不了编辑状态吧。。

那可以加个编辑按钮吗，就算是在电脑上我也觉得按钮要比快捷键方便

**Comment by iuv** [comment]
>  那可以加个编辑按钮吗，就算是在电脑上我也觉得按钮要比快捷键方便

可以在右下角加一个，但你不觉得按快捷键更方便吗，特别是只有一个“e”键的情况下 也不用组合键

**Comment by xovow** [comment]
> > 那可以加个编辑按钮吗，就算是在电脑上我也觉得按钮要比快捷键方便
> 
> 可以在右下角加一个，但你不觉得按快捷键更方便吗，特别是只有一个“e”键的情况下 也不用组合键

可能是我不太习惯吧😂

**Comment by iuv** [comment]
按钮加上了 右下角  另外移动端简单兼容了一下

**Comment by xovow** [comment]
> 按钮加上了 右下角 另外移动端简单兼容了一下

好的，辛苦了😘

**Comment by iuv** [comment]
导入收藏功能加上了

**Comment by xovow** [comment]
![image](https://user-images.githubusercontent.com/78305714/228805691-2d2b240c-7c68-4fb2-a9a4-a7e8fae767e4.png)
为啥手机上是正常的，手机浏览器打开电脑模式也是正常的，但在电脑上看却是这样的？电脑浏览器是百分浏览器

**Comment by iuv** [comment]
@2584191127  我本地访问你部署这个是正常的啊  我用的chrome

**Comment by 2584191127** [comment]
> @2584191127 我本地访问你部署这个是正常的啊 我用的chrome

找到问题了，是被广告规则拦截了

**Comment by xovow** [comment]
> ![image](https://user-images.githubusercontent.com/78305714/228805691-2d2b240c-7c68-4fb2-a9a4-a7e8fae767e4.png) 为啥手机上是正常的，手机浏览器打开电脑模式也是正常的，但在电脑上看却是这样的？电脑浏览器是百分浏览器



> @2584191127 我本地访问你部署这个是正常的啊 我用的chrome

这个问题解决了。
另外请问一下我想实现一个链接一行和收起分组应该怎么弄？

**Comment by iuv** [comment]
一个链接一行这个你就改链接css样式就行
收起分组的话加两个方法实现一下控制分组的css样式

**Comment by xovow** [comment]
> 一个链接一行这个你就改链接css样式就行 收起分组的话加两个方法实现一下控制分组的css样式

没学过css，不会啊😭

**Comment by iuv** [comment]
index.css 第17行删除就变成一行一个链接了
收起的话麻烦点，现在的样式收起也不好看，我试了一下收起也至少要显示一行的内容

**Comment by xovow** [comment]
> index.css 第17行删除就变成一行一个链接了 收起的话麻烦点，现在的样式收起也不好看，我试了一下收起也至少要显示一行的内容

那能用html的detail标签来实现吗

**Comment by iuv** [comment]
这个到不用  改一下样式就行了 建议学习一下css  不复杂

**Comment by xovow** [comment]
> 这个到不用 改一下样式就行了 建议学习一下css 不复杂

在准备考研，没有多少时间学

**Comment by iuv** [comment]
加油！ 先上岸要仅

**Comment by xovow** [comment]
> 加油！ 先上岸要仅

嗯，谢谢
